[qa] Add openwisp-utils-qa-checks
openwisp/django-owm-legacy pull request #4
Opened 2020-01-02 13:27 UTC by waleko

Add `openwisp-utils-qa-checks` (related to openwisp/openwisp-utils#63 for this repo)

2020-01-02 14:10 UTC, waleko commented
Travis is failing, as `django-models-utils` is v4.0.0, but openwisp-utils wants it to be <3.3.0 (fix it in openwisp-utils?)

2020-01-09 12:21 UTC, nemesifier requested changes

2020-01-09 12:21 UTC, nemesisdesign commented on requirements-test.txt
> +openwisp-utils[qa]>=0.3.0
use 0.3.1

2020-01-10 10:24 UTC, atb00ker commented on requirements-test.txt
> +openwisp-utils[qa]>=0.3.1
Lol, this might be a little frustrating but 3.2 got released, can you please update again? :joy:

2020-01-22 17:45 UTC, waleko commented
Updated to 0.4.1

2020-12-09 17:47 UTC, merged